coverage:
  status:
    project:
      default:
        # PR branches do not run network tests of individual data sources,
        # which results in an apparent coverage drop of 2.84 percent
        threshold: 3%
