language: python

dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coverage codecov pytest-cov

script: pytest --cov=./ --remote-data

after_success:
  - coverage combine
  - codecov

notifications:
  email: false
