language: python
os: linux
dist: bionic

branches:
  only:
  - master

jobs:
  include:
  # Linux jobs
  - python: 3.7.0  # earliest
  - python: 3.7
  - python: 3.8
  - python: 3.8-dev
  # Non-linux jobs; Python configured below
  - os: osx
    language: objective-c  # Only language provided
    # Homebrew's Python is installed at this location
    env: PATH=/usr/local/opt/python@3.7/bin:$PATH
  - os: windows
    language: shell
    # Chocolatey installs Python to this location
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH


install:
# Install Python & pip on macOS and Windows
- |-
  case $TRAVIS_OS_NAME in
    windows)
      choco install --no-progress python3
      python -m pip install --upgrade pip ;;
  esac
# All platforms
# - pip3 install --upgrade pip  # commented; this errors the macOS build
- pip3 install --requirement requirements.txt
- pip3 install --editable .[cache,docs,tests]

script: >
  pytest
  -ra
  --verbose
  -m "not experimental"
  --cov sdmx --cov-report term-missing

after_success:
- coverage combine
- codecov

notifications:
  email: false
